### ISSUE TITLE
Fix readMe.

### ISSUE THREAD

**Issue by fcat97** [vipafattal/TajweedParser#2]
fix this,
```gradle
implementation 'com.github.vipafattal:TajweedParser:1.0.0.1'
```

to this,
```gradle
implementation 'com.github.vipafattal:TajweedParser:1.0.1'
```

**Comment by fcat97** [comment]
Library is not working at all. Gradle says, cannot resolve `'com.github.vipafattal:TajweedParser:1.0.0.1'`

**Comment by vipafattal** [comment]
Sorry for the inconvenience, now it should be working under:
`'com.github.vipafattal:TajweedParser:1.0.1'`
