### ISSUE TITLE
Provide java version

### ISSUE THREAD

**Issue by ogigpermana** [vipafattal/TajweedParser#3]
i am creating Quran app using native java, how to implement this using java programming language, thanks in advance

**Comment by vipafattal** [comment]
Please refer back for the readme I have just updated it

**Comment by ogigpermana** [comment]
> Please refer back for the readme I have just updated it

hello sir... I can't download your library the notification in my terminal said can not find com bla bla bla.... event though the jitpack.io was setup

**Comment by ogigpermana** [comment]
![16432369057377826422208727967082](https://user-images.githubusercontent.com/27065956/151259404-877985f4-a9cb-435a-a550-649fcb4dfdf5.jpg)

**Comment by vipafattal** [comment]
Jitpack must be inside `allprojects` body, not `dependencies` :

just put this above `task clean`

```groovy
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
        }
    }
}
```
